FROM ubuntu:22.04@sha256:dfd64a3b4296d8c9b62aa3309984f8620b98d87e47492599ee20739e8eb54fbf

RUN apt-get -y update
RUN apt-get -y install clang-format-14
RUN ln -s /bin/clang-format-14 /bin/clang-format

USER 1000
WORKDIR /tetragon

ENTRYPOINT ["clang-format"]
CMD ["--help"]
