FROM docker.io/golangci/golangci-lint:v1.54.1@sha256:0029334ac23281a0519b6d263aa95fd92f06d20fde5bcf8a1754e5c30d18949c
RUN apt-get -y update
RUN apt-get -y install libz-dev libelf-dev

#- vi: ft=dockerfile -#
