FROM ubuntu:22.04 as clang-builder
WORKDIR /go/src/github.com/cilium/tetragon
RUN apt-get update
RUN apt-get install -y clang-13 llvm-13 make
RUN ln -vsnf /usr/lib/llvm-13/bin/clang /usr/bin/clang
RUN ln -vsnf /usr/lib/llvm-13/bin/llc /usr/bin/llc
