name: Check docs links

on:
  pull_request:
    paths:
      - 'docs/content/**.md'
      - '.github/workflows/check-links-pr.yaml'

jobs:
  links-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
        with:
          fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@3d92e2fd556bef7470d7e2a6aea63141183c20a6
        with:
          hugo-version: '0.111.2'
          extended: true

      - name: Serve the Hugo website
        working-directory: docs
        run: hugo server &

      - name: Wait for server to be ready
        uses: nick-invision/retry@943e742917ac94714d2f408a0e8320f2d1fcafcd
        with:
          timeout_seconds: 2
          max_attempts: 10
          retry_wait_seconds: 3
          command: |
            set -e
            curl -s http://localhost:1313 > /dev/null

      - name: Links Checker
        id: lychee
        uses: lycheeverse/lychee-action@21b2b78c236322f7dcf5b8dbddaa6442f39c2f32
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          args: --base http://localhost:1313 --exclude cilium.herokuapp.com docs/content
          fail: true
          format: json

