name: Tetragon Go Test
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 40
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    steps:
    - name: Install Go
      uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4
      with:
        go-version: '1.18.3'

    - name: Checkout code
      uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      with:
        path: go/src/github.com/cilium/tetragon/

    - name: Install dependencies
      run: |
        sudo apt-get install libelf-dev netcat-traditional libcap-dev gcc

        sudo sed -i '/secure_path/d' /etc/sudoers
        sudo sed -i '/env_reset/d' /etc/sudoers

        echo `which clang`
        echo `which llc`
        echo `clang --version`


    - name: Ensure BPF programs pass verifier
      run: |
        cd go/src/github.com/cilium/tetragon/
        make verify

    - name: Run go tests
      env:
        GOPATH: /home/runner/work/tetragon/tetragon/go
        SUDO: sudo -E
      run: |
        cd go/src/github.com/cilium/tetragon/
        make check-copyright
        sudo -E echo "run go tests: " `uname -a`
        sudo -E go mod verify
        sudo -E GO111MODULE=off go get -u golang.org/x/lint/golint
        export TETRAGON_LIB=$(realpath "bpf/objs/")
        make test

    - name: Upload Tetragon logs
      if: failure()
      uses: actions/upload-artifact@65d862660abb392b8c4a3d1195a2108db131dd05
      with:
        name: tetragon-json
        path: /tmp/tetragon.gotest*
        retention-days: 5

    - name: Upload bugtool dumps
      if: failure()
      uses: actions/upload-artifact@65d862660abb392b8c4a3d1195a2108db131dd05
      with:
        name: tetragon-bugtool
        path: /tmp/tetragon-bugtool*
        retention-days: 5
