name: Renovate
on:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0/15 * * * *'
  workflow_dispatch:
    inputs:
      renovate_log_level_debug:
        type: boolean
        default: false

jobs:
  renovate:
    runs-on: ubuntu-latest
    env:
      buildx_version: 'v0.10.5'
    steps:
      - name: Get token
        id: get_token
        uses: cilium/actions-app-token@350a14155dd9be79227f081310f4d77fdf792e76 # v0.21.0
        with:
          APP_PEM: ${{ secrets.private_key }}
          APP_ID: ${{ secrets.app_id }}

      # buildx is not installed in the renovate container image and we need it
      # for the postUpgradeTasks's commands. We take advantage of the fact that
      # the renovate GitHub action mounts the /tmp folder in the container to
      # transfer the docker CLI plugin binary.
      - name: Cache Buildx CLI plugin download
        id: cache-buildx
        uses: actions/cache@v3
        with:
          path: /tmp/docker-buildx
          key: ${{ runner.os }}-${{ env.buildx_version }}-buildx

      - name: Download and set permissions for buildx
        if: steps.cache-buildx.outputs.cache-hit != 'true'
        run: |
          curl -L -o /tmp/docker-buildx https://github.com/docker/buildx/releases/download/${{ env.buildx_version }}/buildx-${{ env.buildx_version }}.linux-amd64
          chmod +x /tmp/docker-buildx

      # this is not strictly necessary but makes the renovate postUpgradeTasks's
      # commands shorter and understandable
      - name: Create and set permissions for install buildx bash script
        run: |
          echo '#!/bin/bash' > /tmp/install-buildx
          echo 'DIR="$HOME/.docker/cli-plugins"' >> /tmp/install-buildx
          echo 'mkdir -p "$DIR" && ln -sf /tmp/docker-buildx "$DIR/docker-buildx"' >> /tmp/install-buildx
          chmod +x /tmp/install-buildx

      # renovate clones the repository again in its container fs but it needs
      # the renovate configuration to start.
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@f9a5a67d4271f326b1e80695ea86dd9398b61d58 # v38.1.0
        env:
          LOG_LEVEL: ${{ github.event.inputs.renovate_log_level_debug == 'true' && 'DEBUG' || 'INFO' }}
        with:
          configurationFile: .github/renovate.json5
          token: '${{ steps.get_token.outputs.app_token }}'
          mount-docker-socket: true

